server:
  port: 8090

# 分组任务配置
chatbot-api:
  launchList: group01 # 启动几组,就配置几组,中间用逗号分割group01,group02,...
  group01:
    groupName: Chatgpt_AI
    groupId:  # 知识星球ID
    cookie: # 知识星球个人cookie信息
    openAiKey: # 自行申请 https://beta.openai.com/overview
    cronExpression: MC8zMCAqICogKiAqID8= # 执行的频次配置，参考：cron.qqe2.com base64加密